export const students = [
  {
    firstName: "Olumide",
    lastName: "Oladimeji",
    gender: "Male",
    age: 27,
    level: 400,
    score: 85,
    department: "Computer Science",
    courses: ["Hardware", "Software", "Math", "Networking"],
  },
  {
    firstName: "Oluchi",
    lastName: "Okeke",
    gender: "Female",
    age: 25,
    level: 300,
    score: 90,
    department: "Theatre Arts",
    courses: ["English", "History", "Drama", "Music"],
  },
  {
    firstName: "Godswill",
    lastName: "Hussein",
    gender: "Male",
    age: 21,
    level: 200,
    score: 95,
    department: "Pharmacy",
    courses: ["Physics", "Biology", "Math", "Chemistry"],
  },
  {
    firstName: "Joy",
    lastName: "Bello",
    gender: "Female",
    age: 23,
    level: 200,
    score: 80,
    department: "Law",
    courses: ["Literature", "History", "Philosophy"],
  },
  {
    firstName: "Favour",
    lastName: "Bassey",
    gender: "Female",
    age: 24,
    level: 300,
    score: 88,
    department: "Medicine",
    courses: ["Anatomy", "Physiology", "Biochemistry"],
  },
];
